image: quay.io/fenicsproject/pipelines

pipelines:
  default:
    - step:
        script:
          - pip2 install .
          - pip3 install .
          - cd test/
          - python2 -m pytest -v .
          - git clean -fdx .
          - python3 -m pytest -v .
