image: ubuntu:16.04

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y
              g++
              git
              swig
              python-dev python-pip python-pytest python-setuptools
              python3-dev python3-pip python3-pytest python3-setuptools
              --no-install-recommends
          - pip2 install .
          - pip3 install .
          - cd test/
          - python2 -m pytest -v .
          - git clean -fdx .
          - python3 -m pytest -v .
