#!/usr/bin/env python
#
# This script prints all modules found in the instant cache

__author__ = "Martin Alnes (martinal@simula.no)"
__date__ = "2008-09-02 -- 2008-09-03"
__copyright__ = "Copyright (C) 2008 Martin Alnes"
__license__  = "GNU GPL version 3 or any later version"

import os, sys, shutil, tempfile, glob
try:
    import instant
except:
    print "Instant not installed, exiting..."
    sys.exit(1)

modules = instant.cached_modules()
print "Found %d modules in Instant cache:" % len(modules)
for module in modules:
    print module

